name: Deploy DEV

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    environment: dev

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Application Repo
        uses: actions/checkout@v4

      - name: Checkout Platform CDK Repo
        uses: actions/checkout@v4
        with:
          repository: cloud-tech-86/cloud-platform-cdk
          path: cloud-platform-cdk

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Platform Library
        run: |
          cd cloud-platform-cdk
          npm install
          npm run build

      - name: Install Application Dependencies
        run: npm install

      - name: Install Platform Library Into Application
        run: npm install ./cloud-platform-cdk

      - name: Verify Platform Library
        run: npm list @cloudtech/platform-cdk

      - name: Build Application
        run: npm run build

      - name: Run Unit Tests
        run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::786359465516:role/Github-OIDC-Role
          aws-region: ap-south-1

      - name: CDK Diff
        run: npx cdk diff -c env=dev

      - name: CDK Deploy
        run: npx cdk deploy -c env=dev --require-approval never