name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Application Repo
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Checkout Platform CDK
=======
      - name: Checkout Platform CDK Repo
>>>>>>> 8677905 (Update destroy workflow)
        uses: actions/checkout@v4
        with:
          repository: cloud-tech-86/cloud-platform-cdk
          path: ../cloud-platform-cdk

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

<<<<<<< HEAD
      - name: Install Platform CDK
        run: |
          cd ../cloud-platform-cdk
          npm ci
          npm run build

      - name: Install App Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

=======
      - name: Build Platform Library
        run: |
          cd cloud-platform-cdk
          npm install
          npm run build

      - name: Install Application Dependencies
        run: npm install

      - name: Install Platform Library Into Application
        run: npm install ./cloud-platform-cdk

      - name: Verify Platform Library
        run: |
          npm list @cloudtech/platform-cdk

      - name: Build Application
        run: npm run build

>>>>>>> 8677905 (Update destroy workflow)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::786359465516:role/Github-OIDC-Role
          aws-region: ap-south-1

<<<<<<< HEAD
      - name: Destroy Stack
        run: npx cdk destroy --all --force
=======
      - name: Destroy Infrastructure
        run: npx cdk destroy --all --force
>>>>>>> 8677905 (Update destroy workflow)
